import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Benergak?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <div className="flex justify-between items-center py-2 px-4 border-4 border-black">
          <div className="font-cursive text-[32px]">Benergak</div>
          <div className="bg-black px-9 py-2 items-center justify-center text-white font-sans font-bold">
            Login
          </div>
        </div>

        {/* Jumbotron */}
        <div className="pt-20 pb-28 border-x-4 border-b-4 w-auto border-black">
          <div className="font-cursive text-[90px] lg:text-[120px] text-center">Benergak</div>
          <Link href={`/about`}>
            <div className="text-center flex mt-4">
                <div className="bg-white text-[32px] justify-center text-center mx-auto py-3 px-20 font-bold font-sans border-2 border-black shadow-solid-primary hover:shadow-none hover:bg-black hover:text-white">Mulai</div>
            </div>
          </Link>
        </div>

        <div>

        </div>
      </main>
    </div>
  )
}
